/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jenkins.pipeline.test.gradle;

import java.util.ArrayList;
import java.util.Set;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        RandomMethods randomMethods = new RandomMethods();
        System.out.println(new App().getGreeting());


        int i=0;
        if(false){
            randomMethods.add();
        }
    }
}
