/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jenkins.pipeline.test.gradle;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();

        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
        for (int i = 0; i < 10; i++) {

        }
    }

//    @Test
//    public void failedTest(){
//        assertTrue(false);
//    }
}
